spring.application.name=Final

spring.datasource.url=jdbc:mysql://localhost:3306/student_mgmt_v7
spring.datasource.username=root
# password may depend on your localhost password 
# in my case my password is admin -wytm

spring.datasource.password=thazinmoe2006
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=e13932438@gmail.com
spring.mail.password=fbqzklcoppgfcwmf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#please do not delete it
#ilWVdyTfgHEqhpChJHNZCPJcEdQbhQrn

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB



